// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMs_lfmU20HEIJ2hB7pFp8iClG7gp6j84',
    appId: '1:522827634338:web:1ecbbce716309e956ae9fb',
    messagingSenderId: '522827634338',
    projectId: 'vybe-ae7b5',
    authDomain: 'vybe-ae7b5.firebaseapp.com',
    storageBucket: 'vybe-ae7b5.firebasestorage.app',
    measurementId: 'G-HKY7QPB531',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26J0hMTdHOJ8tTzRf71tF36VBWafTRJY',
    appId: '1:522827634338:android:c1e5dbce89b0aab06ae9fb',
    messagingSenderId: '522827634338',
    projectId: 'vybe-ae7b5',
    storageBucket: 'vybe-ae7b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWv1FM_mK4w-Nspx9iItoCec6li2qzfeo',
    appId: '1:522827634338:ios:9b0a9035ecb824c16ae9fb',
    messagingSenderId: '522827634338',
    projectId: 'vybe-ae7b5',
    storageBucket: 'vybe-ae7b5.firebasestorage.app',
    iosBundleId: 'com.example.vybe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWv1FM_mK4w-Nspx9iItoCec6li2qzfeo',
    appId: '1:522827634338:ios:9b0a9035ecb824c16ae9fb',
    messagingSenderId: '522827634338',
    projectId: 'vybe-ae7b5',
    storageBucket: 'vybe-ae7b5.firebasestorage.app',
    iosBundleId: 'com.example.vybe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMs_lfmU20HEIJ2hB7pFp8iClG7gp6j84',
    appId: '1:522827634338:web:02dde2b238912c476ae9fb',
    messagingSenderId: '522827634338',
    projectId: 'vybe-ae7b5',
    authDomain: 'vybe-ae7b5.firebaseapp.com',
    storageBucket: 'vybe-ae7b5.firebasestorage.app',
    measurementId: 'G-RYJ0H2V444',
  );
}
